#!/bin/sh

#Hard coding
prediction_method="IEDB_recommended"

output_file=$1
fasta_file=$2
allele_file=$3
temp_input=$4
file_no=$1

echo "*** Running compute peptides for file $file_no" >> $LOG_FILE


#Add title to new output file 
echo "## IEDB T-cell Epitopes-MHC I binding predictions" > $output_file

# function to run MHC 1 program with different allele and length
run_prediction () {

	#Read the allele file
	while read allele_line           
	do
		count=0
      
		#split the line via ,
		for i in  $allele_line 
		do
			if [ $count == 0 ]
			then
				mhc_allele=$i   
			else
   			length=$i
			fi

			count=`expr $count + 1` 
 		done

				
		echo "BINDING_TEST $mhc_allele $length" >> $output_file
 
		predict_binding.py $prediction_method $mhc_allele  $length $temp_input 1>>$output_file 2>>$LOG_FILE || exit 1 

           
	done < $allele_file   
   
}

#Global variables
IFS=","
first_seq=1

#Read the fasta file and create temporary input file
while read line           
do

	echo $line | grep -c '>' > /dev/null

	if [ $? -eq 0 ]
	then
 
		#Check it this is the first sequence
		if [ $first_seq == 1 ]
		then
 			first_seq=0
  		else
   			run_prediction	
		fi
		
		echo $line > $temp_input
		#Add sequence identifier to output file
		echo "$line" >> $output_file

 
	else
 		echo $line >> $temp_input
	fi


done < $fasta_file

#compute the last sequence
run_prediction		


