#!/bin/sh
#Resource used: MHC II
resource=MHCII
short_name=mhcii

#Get command prompts
proteome_fasta=$1
proteome_dir=$2
script_dir=$3
out_dir=$4
common_dir=$5
prog_dir=$6
allele_file=$7
train_dir=$8
train_file=$9
evidence_dir=${10}

#hard coding
bg_mode=1
split_by=`nproc` #default split value is number of CPUs


echo "Splitting FASTA file for " $resource >> $LOG_FILE
perl $common_dir/split_fasta.pl $proteome_dir/$proteome_fasta $split_by $out_dir
no_of_files=$?
if [ $no_of_files == 0 ]; then
	exit 1
fi

#Main loop for writing scripts
for file_no in  $(seq 1 $no_of_files)
do

	#Write the error function to script
	$common_dir/error_script "$file_no" "$script_dir"

	#Program section
	echo "echo Running file $file_no for $resource >> $LOG_FILE" >> $script_dir/script$file_no

	echo "script_step=\"executing MHC II run script for $file_no\"" >> $script_dir/script$file_no
	echo "$prog_dir/compute_peptides  $out_dir/$short_name$file_no $out_dir/file_$file_no.fasta  $allele_file $out_dir/temp$file_no $file_no\
	2>> $LOG_FILE || error_exit" >> $script_dir/script$file_no

done

## Run scripts for chromomsomes
$common_dir/run_scripts "$resource" "$no_of_files" "$script_dir" "$bg_mode" || exit 1

##Tidy up
echo "Tidying up for " $resource >> $LOG_FILE
cat $out_dir/${short_name}* > $out_dir/out_${short_name} || exit 1
#rm  $out_dir/${short_name}* || exit 1
#rm  $out_dir/*.fasta || exit 1

file_no="a"

#Write the error function to script
$common_dir/error_script "$file_no" "$script_dir"

#Program section
echo "script_step=\"executing extract_mhcii_output.pl\"" >> $script_dir/script$file_no
echo "perl $prog_dir/extract_mhcii_output.pl  $out_dir/out_${short_name} $out_dir \
2>> $LOG_FILE || error_exit" >> $script_dir/script$file_no

echo "script_step=\"executing extract_mhcii_stats.pl\"" >> $script_dir/script$file_no
echo "perl $prog_dir/extract_mhcii_stats.pl $out_dir \
2>> $LOG_FILE || error_exit" >> $script_dir/script$file_no

echo "script_step=\"executing mhcii_ml.pl\"" >> $script_dir/script$file_no
echo "perl $prog_dir/mhcii_ml.pl  $out_dir/out_${short_name} $out_dir $train_dir \
2>> $LOG_FILE || error_exit" >> $script_dir/script$file_no

echo "script_step=\"executing get_predictors.pl\"" >> $script_dir/script$file_no
echo "perl $prog_dir/get_predictors.pl  $allele_file $out_dir \
2>> $LOG_FILE || error_exit" >> $script_dir/script$file_no

#Make script executable
chmod +x $script_dir/script$file_no
	
#Run script
$script_dir/script$file_no || exit 1 


#Run the Rscripts
Rscript $prog_dir/mhcii_wrapper.R "$prog_dir" "$out_dir" "$train_dir/$train_file" || exit 1


#extract predictions
echo "Executing extract_predictions.pl" >> $LOG_FILE
perl $prog_dir/extract_predictions.pl  $out_dir $evidence_dir 2>> $LOG_FILE || exit 1









